services:
  bot:
    build: .
    container_name: bot
    volumes:
      - ./downloads/:/downloads/
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_network
  
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge

volumes:
  grafana_data: