on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Add SSH Key
              run: |
                echo "${{ secrets.KEY_HOST}}" > private_key.pem
                chmod 400 private_key.pem
            - name: Deploy to EC2
              run: |
                ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.NAME_HOST }}@${{ secrets.IP_HOST }} << 'EOF'
                  cd ~
                  rm -rf bot
                  git clone https://github.com/andrii-br/Tg-bot-pdf2doc.git bot
                  cd bot

                  echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
                  
                  docker-compose down || true
                  docker-compose up --build -d
                  sleep 5
                  docker ps -a
                EOF

